language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t home/trungnq1/repositories/my-app-test -f Dockerfile.dev .

script:
  - docker run -e CI=true home/trungnq1/repositories/my-app-test npm run test

after_success:
  - docker build -t home/trungnq1/repositories/my-app-test .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push home/trungnq1/repositories/my-app-test
